### PR TITLE
Extractselectionandformat

### PR DESCRIPTION
**Pull request by Mjos12002**
I have added a function to produce the object to be used for generating the report. Just click on the generate report button and check the console

### CODE REVIEW

**Review by tomzemp — CHANGES_REQUESTED** [review]
Hi @Mjos12002. Good start. Looks like the organisation unit information is working well.

There are some issues to fix here:
- you are taking the data sets and data elements from those available in the configuration, regardless of the user's group selection. As mentioned in the ticket, you need to get the group id that the user selected and then pass that and the configuration to the [function](https://github.com/hisprwanda/who-data-quality-annual-report/blob/main/src/utils/utils.js#L15) that Maurice wrote in order to get the data sets and data elements relevant to the selected group id
- you are storing the selected period as the name of the period (e.g. `October 2021 - September 2022`). You need to be using the ISO string (e.g. `2021Oct`) for the period as that is what is used in an analytics request. See: https://docs.dhis2.org/en/full/develop/dhis-core-version-master/developer-manual.html#webapi_date_perid_format
- Your method for calculating periods will not work when you have a non calendar year period (e.g. if you have Oct 2021 - Sep 2022 and not 2022). It would be best to use generateFixedPeriods function and then select the preceding periods, but given that yearly types are the only ones supported, you could also modify your approach to handle the other yearly period types.
- your current period array has a mix of strings and numbers. They should all be strings.

**Comment by Mjos12002** [comment]
> Hi @Mjos12002. Good start. Looks like the organisation unit information is working well.
> 
> There are some issues to fix here:
> 
>     * you are taking the data sets and data elements from those available in the configuration, regardless of the user's group selection. As mentioned in the ticket, you need to get the group id that the user selected and then pass that and the configuration to the [function](https://github.com/hisprwanda/who-data-quality-annual-report/blob/main/src/utils/utils.js#L15) that Maurice wrote in order to get the data sets and data elements relevant to the selected group id
> 
>     * you are storing the selected period as the name of the period (e.g. `October 2021 - September 2022`). You need to be using the ISO string (e.g. `2021Oct`) for the period as that is what is used in an analytics request. See: https://docs.dhis2.org/en/full/develop/dhis-core-version-master/developer-manual.html#webapi_date_perid_format
> 
>     * Your method for calculating periods will not work when you have a non calendar year period (e.g. if you have Oct 2021 - Sep 2022 and not 2022). It would be best to use generateFixedPeriods function and then select the preceding periods, but given that yearly types are the only ones supported, you could also modify your approach to handle the other yearly period types.
> 
>     * your current period array has a mix of strings and numbers. They should all be strings.

**Comment by Mjos12002** [comment]
@tomzemp thanks for the comments. What do you think is best approache to use the function created by @mauricejulesm as it belongs in a separate branch?

**Comment by tomzemp** [comment]
> What do you think is best approache to use the function created by @mauricejulesm as it belongs in a separate branch?

@Mjos12002: It's merged into `main` branch (https://github.com/hisprwanda/who-data-quality-annual-report/blob/main/src/utils/utils.js#L15), so if this branch is behind the `main` branch, you can merge in `main` and then use the function

**Comment by Mjos12002** [comment]
> Hi @Mjos12002. Good start. Looks like the organisation unit information is working well.
> 
> There are some issues to fix here:
> 
>     * you are taking the data sets and data elements from those available in the configuration, regardless of the user's group selection. As mentioned in the ticket, you need to get the group id that the user selected and then pass that and the configuration to the [function](https://github.com/hisprwanda/who-data-quality-annual-report/blob/main/src/utils/utils.js#L15) that Maurice wrote in order to get the data sets and data elements relevant to the selected group id
> 
>     * you are storing the selected period as the name of the period (e.g. `October 2021 - September 2022`). You need to be using the ISO string (e.g. `2021Oct`) for the period as that is what is used in an analytics request. See: https://docs.dhis2.org/en/full/develop/dhis-core-version-master/developer-manual.html#webapi_date_perid_format
> 
>     * Your method for calculating periods will not work when you have a non calendar year period (e.g. if you have Oct 2021 - Sep 2022 and not 2022). It would be best to use generateFixedPeriods function and then select the preceding periods, but given that yearly types are the only ones supported, you could also modify your approach to handle the other yearly period types.
> 
>     * your current period array has a mix of strings and numbers. They should all be strings.

@tomzemp I have addressed those 3 points raised, please have a look.

**Review by tomzemp — APPROVED** [review]
Looks like this is working well now! 🎉

**Pull request merged**
