### PR TITLE
chore: add requests for Section 1 of annual report

### PR DESCRIPTION
**Pull request by tomzemp**
See [RWDQA-20](https://dhis2.atlassian.net/jira/software/c/projects/RWDQA/issues/RWDQA-20)

This ticket shows how requests can be made for Section 1 of the annual report (provided that we have the relevant variables to pass to the queries).

I do not know where this code should eventually live in the app; this is just an example to show how the requests can be restructured.

### CODE REVIEW

**Review by Mjos12002 — COMMENTED** [review]
I have reviewed the codes and they look good, I suggest we invoke the generateReport() method when the reporting component/page loads. Let us test it asap

**Review by mauricejulesm — COMMENTED** [review]
This looks good & i was able to use the results of this functionality in #18 successfully. 
About where this code should live, we can discuss as a team.

**Comment by tomzemp** [comment]
> I have reviewed the codes and they look good, I suggest we invoke the generateReport() method when the reporting component/page loads. Let us test it asap

Thanks @Mjos12002 . We probably don't want to invoke `generateReport()` as soon as the page loads because the selections won't be present yet. Probably better to wait until user makes selections and clicks on "generate" button.

Connecting this work with the selections work you've done and the calculations work Maurice is done is part of this ticket: https://dhis2.atlassian.net/browse/RWDQA-27

**Review by mauricejulesm — APPROVED** [review]
Good to go!

**Pull request merged**
