### PR TITLE
fix: numerators configuration [RWDQA-68]

### PR DESCRIPTION
**Pull request by KaiVandivier**
Addresses:
* [RWDQA-68: editing a numerator creates a duplicate](https://dhis2.atlassian.net/browse/RWDQA-68)
* [RWDQA-69: numerator codes are reused](https://dhis2.atlassian.net/browse/RWDQA-69)
* [RWDQA-70: new numerator: dataID not set](https://dhis2.atlassian.net/browse/RWDQA-70)
* [RWDQA-74: data sets not added to configurations' `dataSets`](https://dhis2.atlassian.net/browse/RWDQA-74) partially -- new dataSets are added, but not yet deleted when the last member numerator is deleted (I considered this a functional MVP)

Other inclusions:
* Optimized final-form
* Smoother UI
* Populating metadata names in the numerator list view
* Choosing data element _details_ in the create/edit form
* "Clear" functionality at parity with old app

Expected follow-ups:
* Clear unused data sets in configurations ([RWDQA-81](https://dhis2.atlassian.net/browse/RWDQA-81))
* Adding fields to choose "Indicator" data items ([RWDQA-80](https://dhis2.atlassian.net/browse/RWDQA-80))
* Form validation for the create/edit form (making sure a user selects a data item, one or more data sets, and a variable for completeness) ([RWDQA-79](https://dhis2.atlassian.net/browse/RWDQA-79))
* Revise "clear" functionality; use a disabled "delete" button ([RWDQA-11](https://dhis2.atlassian.net/browse/RWDQA-11))

### CODE REVIEW

**Review by tomzemp — APPROVED** [review]
Great job 👏! This is looking really good and addresses the issues that we had. I think the other follow-up points that you've identified are okay to address as follow-ups (the indicators work I might table to post-MVP as it seems RW MoH doesn't need that functionality (to confirm))

I've tested this both on our demos.dhis2.org/dq and on online.hisprwanda.org/hmisdev and it's working well. I've also read through the code (a bit more cursorily than usual); code looks good, and while there were a couple of points that I thought about a small comment, I don't think any of my suggestions would add much improvement, so I have no specific code comments for now.

There were a couple of points I noticed (we can discuss and decide if we want to address them; if yes, we can do it separate from this PR)

- there's a bit of a lag between the UI/query completion on the various DataElementSelect, VariableSelect etc., this can lead to situations where you can select e.g. a data element operand that is not relevant to the the data element, which leads to error (I think maybe our selects are updated so that this error might only actually crash the app in dev mode?):
numerator_selects
Maybe we could just hide the fields until the requests complete? Or we can disable them while the requests are in progress?



- when I select a value for details and open up again to edit, I get that the numerator is mapped to undefined. This is a minor point in comparison to the fact that I forgot to account for the cocs in the calculations  🙃 (https://dhis2.atlassian.net/browse/RWDQA-82) 

- ideally, it would be nice if we could open the edit a numerator and have the existing information populate (I know the current app also doesn't do this, so I think we can skip, but it might be something to add as a potential non-MVP improvement)

**Review by mauricejulesm — APPROVED** [review]
from my test, it's working as described!

**Comment by KaiVandivier** [comment]
Nice, thanks for the good feedback and finding the those bugs!

I think the first two things are fixable in this PR -- I think I know how to fix them without too much work

The third one, pre-populating the data mapping fields, I agree would be very nice, but would take some time given the current design -- I took the design from the old app, which I _think_ is intended to fetch only the necessary metadata to populate the selects on demand, without needing to fetch all the instance's data element groups, data elements, data sets, data element operands, indicator groups, and indicators on each app load. Fetching all that metadata is an option, but maybe also saving the numerator's dataType and dataElementGroup/indicatorGroup would also provide enough information to make the requests to prepopulate it 🤔 either way, here's an issue to follow up in the future: https://dhis2.atlassian.net/browse/RWDQA-84

**Comment by KaiVandivier** [comment]
Fixed issues 1 and 2 🙂 

https://github.com/hisprwanda/who-data-quality-annual-report/assets/49666798/43c85c95-dd9c-4706-8919-e81d306dd179

**Pull request merged**
